#!/usr/bin/expect -f

# Expecting the string and sending the desired input in response
# Change PASS variable accordingly

set PASS "user"

set timeout -1
spawn ./newkeypair.sh
match_max 100000
expect "password for "
send -- "$PASS\r"
expect "Enter file in which to save the key "
send -- "\r"
expect "Overwrite (y/n)? "
send -- "y\r"
expect "Enter passphrase "
send -- "\r"
expect "Enter same passphrase again: "
send -- "\r"
expect eof
